version: "3.9"

services:
  pissircd:
    build: "pissircd-docker/"
    volumes:
      - "pissircd:/home/pissircd/unrealircd/data"
      - "./config/unrealircd.conf:/home/pissircd/unrealircd/conf/unrealircd.conf"
      - "./config/server.cert.pem:/home/pissircd/unrealircd/conf/tls/server.cert.pem"
      - "./config/server.key.pem:/home/pissircd/unrealircd/conf/tls/server.key.pem"
    ports:
      - "6667:6667"
      - "6697:6697"
      - "6900:6900"

volumes:
  pissircd:
